backup: add post run check of snapshot size
Also consolidate variables for pre and post check.

Example:
```
Starting Backup of synapse-db with Restic...
CHECK: No backup dir issues found.
using parent snapshot a788efef
Files:           0 new,     0 changed,   172 unmodified
Dirs:            0 new,     0 changed,     5 unmodified
Added to the repository: 0 B   (0 B   stored)
processed 172 files, 3.748 GiB in 0:00
skipped creating snapshot
CHECK: No snapshot issues found.
backup-synapse-db.service: Deactivated successfully.
Finished Backup of synapse-db with Restic.
```

Related postmortem:
https://github.com/status-im/infra-docs/pull/42

Signed-off-by: Jakub Sokołowski <jakub@status.im>

diff --git a/templates/backup-check-script.sh.j2 b/templates/backup-check-script.sh.j2
--- a/templates/backup-check-script.sh.j2
+++ b/templates/backup-check-script.sh.j2
@@ -2,17 +2,23 @@
 # vim: ft=sh
 set -e
 
-if [ -z "$1" ]; then
-    echo "Error: Backup directory path required"
+BACKUP_DIR="${1}"
+MIN_BYTES="${2:-{{ backup_min_bytes_processed }}}"
+MIN_FILES="${3:-{{ backup_min_files_processed }}}"
+
+if [[ -z "${BACKUP_DIR}" ]]; then
+    echo "ERROR: Backup directory path required"
     exit 1
 fi
+DIR_BYTES=$(du -bs "${BACKUP_DIR}" | cut -f1)
+DIR_FILES=$(find "${BACKUP_DIR}" -type f | wc -l)
 
-BACKUP_DIR="$1"
-MIN_SIZE_BYTES="{{ backup_size_threshold_bytes }}"
-
-DIR_SIZE=$(du -bs "${BACKUP_DIR}" | cut -f1)
-
-if [ "${DIR_SIZE}" -lt "${MIN_SIZE_BYTES}" ]; then
-    echo "Error: Backup directory too small (${DIR_SIZE} bytes), minimum size is ${MIN_SIZE_BYTES} bytes"
+if [[ ${DIR_BYTES} -lt ${MIN_BYTES} ]]; then
+    echo "ERROR: Dir too small (${DIR_BYTES} B), minimum size is ${MIN_SIZE_BYTES} B." >&2
     exit 1
 fi
+if [[ ${DIR_FILES} -lt ${MIN_FILES} ]]; then
+    echo "ERROR: Dir with not enough files (${DIR_FILES}), minimum number is ${MIN_FILES}." >&2
+    exit 1
+fi
+echo "CHECK: No backup dir issues found."
